### ISSUE TITLE
docker方式部署后docker run 提示权限不足

### ISSUE THREAD

**Issue by Naylor55** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#101]
Error: EACCES: permission denied, mkdir '/home/node/app/.docusaurus/@easyops-cn/docusaurus-search-local/default'
    at Object.mkdirSync (node:fs:1398:3)
    at module.exports.makeDirSync (/home/node/app/node_modules/fs-extra/lib/mkdirs/make-dir.js:23:13)
    at Object.DocusaurusSearchLocalPlugin [as plugin] (/home/node/app/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js:16:24)
    at initializePlugin (/home/node/app/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:61)
    at async Promise.all (index 9)
    at async initPlugins (/home/node/app/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async loadPlugins (/home/node/app/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/home/node/app/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/home/node/app/node_modules/@docusaurus/core/lib/commands/start.js:44:19)

**Comment by yuluo-yx** [comment]
确实存在此问题，你可以提交 pr 修复这个问题吗？
